config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :categories, only: [:index, :show]

  resources :articles do
    resources :bibliographies, except: [:show]
    resources :footnotes, except: [:show]
    resources :revisions, only: [:index, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: :User
  has_many :footnotes, dependent: :destroy
  has_many :photos
  has_many :bibliographies, dependent: :destroy
  has_many :article_categories
  has_many :revisions
  has_many :categories, through: :article_categories
  has_many :editors, through: :revisions
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/bibliography.rb
class Bibliography < ApplicationRecord
  belongs_to :article
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/footnote.rb
class Footnote < ApplicationRecord
  belongs_to :article
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :article
end

app/models/revision.rb
class Revision < ApplicationRecord
  belongs_to :original_article, :class_name => 'Article'
  belongs_to :article
  belongs_to :editor, class_name: :User
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, foreign_key: :author_id
  has_many :revisions, foreign_key: :editor_id
  has_many :edited_articles, through: :revisions, source: :article
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  # def is_moderator
  #   if current_user == 
  # end
end


# enum role: [:admin, :moderator]
# in user migration: define as an attribute 
# t.integer :role
# in view: if current_user.role == admin

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :authenticate_user!, except: [:index]

  def index
    @articles = Article.all
    @search = Article.ransack(params[:q])
    @articles = @search.result
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @revised_article = Article.new(article_params)

    if @revised_article.save
      @revision = Revision.create(editor_id: current_user.id, article_id: @revised_article.id, original_article_id: @article.id)

      redirect_to article_revisions_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to '/'
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :author_id)
    end

    # polymorphic self ? as revised article???
    #

    # def revision_params
    #   params.require(:revision).permit(:editor_id, :article_id,:original_article_id)
    # end

end

app/controllers/bibliographies_controller.rb
class BibliographiesController < ApplicationController

  def new
    @article = Article.find(params[:article_id]) # Might break. We're testing article_id vs id
    @bibliography = Bibliography.new
  end

  def create
    @article = Article.find(params[:article_id])
    @bibliography = @article.bibliographies.new(bibliography_params)
    if @bibliography.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:article_id])
  end

  def update
    @article = Article.find(params[:article_id])
    @bibliography = @article.bibliographies.find(params[:id])

    if @bibliography.update(bibliography_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @bibliography = @article.bibliographies.find(params[:id])
    @bibliography.destroy
    redirect_to @article
  end

  private
    def bibliography_params
      params.require(:bibliography).permit(:link_url, :title, :body)
    end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/concerns/revisions_controller.rb
class RevisionsController < ApplicationController

  def index
    @article = Article.find(params[:article_id])
    @revision = @article.revisions
    @rev = Revision.all
    p @rev
  end

  def show
    @revisions = Revision.find(params[:id])
  end

end

app/controllers/footnotes_controller.rb
class FootnotesController < ApplicationController

  def new
    @article = Article.find(params[:article_id])
    @footnote = @article.footnotes.new
  end

  def create
    @article = Article.find(params[:article_id])
    @footnote = @article.footnotes.new(footnote_params)

    if @footnote.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:article_id])
    @footnote = @article.footnotes.find(params[:id])
  end

  def update
    @article = Article.find(params[:article_id])
    @footnote = @article.footnotes.find(params[:id])

    if @footnote.update(footnote_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @footnote = @article.footnotes.find(params[:id])
    @footnote.destroy
    redirect_to article_path(@article)
  end

  private
    def footnote_params
      params.require(:footnote).permit(:text, :url)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>

<%= form_for @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_area :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.cktext_area :body, rows: 10, cols: 40, ckeditor: { uiColor: '#AADC6E', toolbar: 'mini' } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_new_article_form.html.erb
<% if user_signed_in? %>

<%= form_for @article do |form| %>
  <%= form.cktext_area :notes, class: 'someclass', ckeditor: { language: 'uk'} %>
  <%= form.cktext_area :content, value: 'Default value', id: 'sometext' %>
  <%= cktext_area :article, :info, cols: 40, ckeditor: { uiColor: '#AADC6E', toolbar: 'mini' } %>
<% end %>


<% end %>

app/views/articles/edit.html.erb
<% if user_signed_in? %>
  <h2>Edit Article</h2>

  <%= render 'form', article: @article %>

  <%= link_to 'Show', @article %> |
  <%= link_to 'Back', articles_path %>
<% end %>

app/views/articles/index.html.erb
Search for an article:
<%= search_form_for @search do |f| %>
  <%= f.label :title_cont %>
  <%= f.search_field :title_cont %>

  <%= f.submit %>
<% end %>


<h1>Articles</h1>

<% if user_signed_in? && current_user.is_moderator  %>

  <% @articles.each do |article| %>
    <%= article.title %>
    <%= raw article.body %>
    <%= link_to 'Show', article %>
    <%= link_to 'Edit', edit_article_path(article) %>
    <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are ya suurrrre?' } %>
    <%= link_to 'Revisions', article_revisions_path(article) %><br><br>
  <% end %>

<% elsif user_signed_in? %>

   <% @articles.each do |article| %>
    <%= article.title %>
    <%= raw article.body %>
    <%= link_to 'Show', article %>
    <%= link_to 'Edit', edit_article_path(article, @revision) %>
    <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are ya suurrrre?' } %>
  <% end %>

<% else %>


  <% @articles.each do |article| %>
    <%= article.title %><br>
    <%= raw article.body %><br><br>
    <%= link_to 'Show', article %>  
  <% end %>

<% end %>


<% if user_signed_in? %>
  <%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>
<h2>Create new article:</h2>

<%= form_for @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_area :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.cktext_area :body, rows: 10, cols: 40, ckeditor: { uiColor: '#AADC6E', toolbar: 'mini' } %>
  </div>

    <div>
    <%= form.label :author_id %><br>
    <%= form.text_area :author_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<div>
  <strong>Title:</strong>
  <%= @article.title %>
</div>

<div>
  <strong>Body:</strong>
  <%= raw @article.body %>
</div>

<div id="footnote">
  <h2> Footnotes </h2>
  <% if @article.footnotes.empty? %>
    <p>
      This article doesn't have any footnotes currently.
      Would you like to <%= link_to 'add some', new_article_footnote_path(@article) %>
    </p>
  <% else %>
    <ol>
      <% @article.footnotes.each do |footnote| %>
        <li>
          <%= "#{footnote.text}: "  %> <a href= <%= footnote.url%> >read more</a>
        </li>
      <% end %>
    </ol>
  <% end %>
</div>

<div id="biobliography">
  <h2> For Further Reading </h2>
  <% if @article.bibliographies.empty? %>
    <p>
      This article doesn't have any bibliographies currently. Would you like to <%= link_to "add some", new_article_bibliography_path(@article) %>
    </p>
  <% else %>
    <ol>
      <% @article.bibliographies.each do |biobliography| %>
        <li>
          <strong> <%= biobliography.title %> </strong>
          <%= "#{biobliography.body} " %> <a href= <%= biobliography.link_url%> >Read more</a>
        </li>
      <% end %>
    </ol>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>

<%= @article.id %>

app/views/bibliographies/_form.html.erb
<% if @bibliography.errors.any? %>
  <div id="error-list">
    <h2>Errors</h2>
  <ul>
    <% @bibliography.errors.full_messages.each do |e| %>
      <li><%= e %></li>
    <% end %>
  </ul>
  </div>
<% end %>

<%= form_for [@article, @bibliography] do |f| %>
  <fieldset>
    <%= f.label :title, "Resource name" %>
    <%= f.text_field :title %>
  </fieldset>

  <fieldset>
    <%= f.label :body, "Brief description" %>
    <%= f.text_field :body %>
  </fieldset>

  <fieldset>
    <%= f.label :link_url, "Link" %>
    <%= f.text_field :link_url %>
  </fieldset>

  <%= f.submit %>

<% end %>

app/views/bibliographies/edit.html.erb
<div class="form-container">
  <%= render 'form' %>

  <%= link_to 'Delete', [@article, @bibliography], method: delete %>
  <%= link_to 'Back', edit_article_path(@article) %>
  <!--  This line can be handled with AJAX to clear and hide this form. Without AJAX, I'm not sure the best what to handle this without erasing other changes to the page. -->
</div>

app/views/bibliographies/new.html.erb
<div class="form-container">
  <%= render 'form' %>

  <%= link_to 'Back to article', @article %>
</div>

app/views/footnotes/_form.html.erb
<% if @footnote.errors.any? %>
  <div id="error-list">
    <h2>Errors</h2>
  <ul>
    <% @footnote.errors.full_messages.each do |e| %>
      <li><%= e %></li>
    <% end %>
  </ul> 
  </div>
<% end %>

<%= form_for [@article, @footnote] do |f| %>

  <%= f.label :text %><br>
  <%= f.text_area :text %><br><br>

  <%= f.label :url %><br>
  <%= f.text_field :url %><br>

  <%= f.submit %>

<% end %> 

app/views/footnotes/edit.html.erb
Edit footnote for <%= @article.title %><br><br>

<%= render 'form' %>

<%= link_to 'Delete', [@article, @footnote],
                        method: :delete,
                        data: { confirm: 'Are you sure?' }
                        %><br>

<%= link_to 'Back', @article %>

app/views/footnotes/new.html.erb
New footnote for <%= @article.title %><br><br>

<%= render 'form' %>

<%= link_to 'Back', @article %>

app/views/revisions/index.html.erb
<% if current_user.is_moderator %>
  <% Revision.where(original_article: @article).each do |revision| %>
  <%= revision.id %>
  <%= revision.editor_id%>
  <%= revision.original_article_id %>
  <%= revision.article_id %>
  <br>
  <% end %>
<% end %>

app/views/revisions/show.html.erb
<% if current_user.is_moderator %>
  
<% end %>